"""Baseline schema — Phase 1.

The baseline creates everything from the SQLAlchemy metadata so the
migration can never drift from the models it ships with. Subsequent
migrations are normal hand/autogenerated diffs against this.

Revision ID: 0001
Revises:
Create Date: 2026-07-12
"""
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # pgvector is used from Phase 2 (document-vault embeddings). The shipped
    # db image includes it; tolerate its absence in dev/CI databases.
    op.execute(
        """
        DO $$
        BEGIN
            CREATE EXTENSION IF NOT EXISTS vector;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'pgvector not available; skipping (needed from Phase 2)';
        END
        $$
        """
    )
    from app.models import Base

    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    from app.models import Base

    Base.metadata.drop_all(bind=op.get_bind())
